# DonutCore Sell Configuration

lore:
  - '&7Worth: &#15e30f$%amount%'

# ACTIONBAR or CHAT or TITLE available (You can choose multiple)
sell-notify-mode:
  - ACTIONBAR
  #- TITLE
  #- CHAT

use-multipliers: true

storage:
  type: SQLITE # SQLITE, MYSQL, YAML

sqlite:
  file: sell-data.db
  table-prefix: sell_

sell-command:
  hand-enabled: false
  inventory-enabled: false

missing-price-not-sellable: false

# Restart your server every time you change this
use-new-sell-menu: false

sell-notify:
  screen:
    title: '&a+$%amount%'
    subtitle: '&7You sold %items% items'
    fade-in: 5
    stay: 40
    fade-out: 10

# GUI title names that should show worth lore (partial match)
worth-lore-whitelist-gui-names:
  - Chest
  - Shulker

# Whether to show the "worth" lore on items
display-worth-lore: true

# If true, lore shows worth for 1 item; if false, lore shows stack worth
worth-lore-per-item: false

# The %vaultmoney_sell_money_formatted% placeholder uses these suffixes
money-suffixes:
  K: 1000
  M: 1000000
  B: 1000000000
  T: 1000000000000
  Q: 1000000000000000

sounds:
  page-switch: ITEM_BOOK_PAGE_TURN
  close-sound: ENTITY_EXPERIENCE_ORB_PICKUP
  click-sound: UI_BUTTON_CLICK
  declined: ENTITY_VILLAGER_NO

disabled-items:
  - BARRIER
  - LIGHT
  - SPAWN_EGG
  - SPAWNER

sell-axe:
  use-countdown: true
  duration-seconds: 259200 # 3 days

  display-name: '&#8e0beeᴀᴍᴇᴛʜʏѕᴛ ѕᴇʟʟ ᴡᴀɴᴅ'
  lore:
    - '&7Instanly Sells All Items in A Chest'
    - '&8Self Destruct:'
    - '&8%countdown%'

  enchantments:
    - MENDING:1
    - EFFICIENCY:5
    - UNBREAKING:3
