# ############################################################
# #                                                          #
# #   #####    ####   ##  ##  ##  ##  ######   ####         #
# #   ##  ##  ##  ##  ### ##  ##  ##    ##    ##            #
# #   ##  ##  ##  ##  ######  ##  ##    ##    ##            #
# #   ##  ##  ##  ##  ## ###  ##  ##    ##    ##  ##        #
# #   #####    ####   ##  ##   ####     ##     ####         #
# #                                                          #
# #    ####    ####   #####   ######                        #
# #   ##  ##  ##  ##  ##  ##  ##                            #
# #   ##      ##  ##  #####   #####                         #
# #   ##  ##  ##  ##  ## ##   ##                            #
# #    ####    ####   ##  ##  ######                        #
# #                                                          #
# #   Author  : Andreilarazboi                              #
# #   Version : 1.0.8                          #
# #   Modules : Sell, Crates, EnderChest                    #
# #                                                          #
# ############################################################

# ============================================================
#  MODULE TOGGLES
#  Enable or disable each module independently.
#  Use /donutcore module <name> <enable|disable> in-game.
# ============================================================
modules:
  crates: true
  sell: true
  enderchest: true
